package com.maldawr.chatsimulator;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.media.AudioAttributes;
import android.media.Ringtone;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Switch;
import android.widget.TextView;
import android.widget.Toast;

public class CustomizationActivity extends Activity {
    private static final int PICK_NOTIFICATION_ICON=901,PICK_HOME_ICON=902,PICK_NOTIFICATION_SOUND=903,PICK_CALL_SOUND=904,PICK_CHAT_IN=905,PICK_CHAT_OUT=906;
    private EditText titleInput; private TextView sizeValue,fontValue,radiusValue,patternValue,soundStatus; private SeekBar sizeSeek,fontSeek,radiusSeek,patternSeek; private ImageView notificationPreview,homePreview; private LinearLayout livePreview; private Ringtone previewRingtone;

    @Override protected void onCreate(Bundle s){super.onCreate(s);buildUi();}
    @Override protected void onDestroy(){stopPreview();super.onDestroy();}

    private void buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xFF0B141A);root.addView(Ui.safetyBanner(this));
        ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(Ui.dp(this,18),Ui.dp(this,14),Ui.dp(this,18),Ui.dp(this,34));
        TextView title=Ui.label(this,"Customization Center",26,true);title.setTextColor(Color.WHITE);body.addView(title);
        TextView sub=Ui.label(this,"Sounds, notification channels, chat themes, icons and behavior for this fictional simulator.",13,false);sub.setTextColor(0xFF8696A0);sub.setPadding(0,Ui.dp(this,4),0,Ui.dp(this,14));body.addView(sub);
        Button intelligence=Ui.button(this,"Conversation intelligence & background activity");intelligence.setOnClickListener(v->startActivity(new Intent(this,IntelligenceSettingsActivity.class)));body.addView(intelligence);

        addSection(body,"Live chat preview");livePreview=new LinearLayout(this);livePreview.setOrientation(LinearLayout.VERTICAL);livePreview.setPadding(Ui.dp(this,12),Ui.dp(this,12),Ui.dp(this,12),Ui.dp(this,12));body.addView(livePreview,new LinearLayout.LayoutParams(-1,Ui.dp(this,150)));refreshLivePreview();

        addSection(body,"Theme presets");LinearLayout presets=new LinearLayout(this);presets.setGravity(Gravity.CENTER);String[] names={"Midnight","Ocean","Violet","Warm","Graphite"};String[] keys={"midnight","ocean","violet","warm","graphite"};for(int i=0;i<keys.length;i++){TextView p=Ui.label(this,names[i],12,true);p.setGravity(Gravity.CENTER);p.setTextColor(Color.WHITE);p.setBackground(Ui.rounded(presetColor(keys[i]),14,this));final String key=keys[i];p.setOnClickListener(v->{CustomizationPrefs.setPreset(this,key);refreshLivePreview();Toast.makeText(this,"Theme: "+((TextView)v).getText(),Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,Ui.dp(this,48),1f);lp.setMargins(Ui.dp(this,2),0,Ui.dp(this,2),0);presets.addView(p,lp);}body.addView(presets);
        fontValue=slider(body,"Message font",CustomizationPrefs.getMessageFontSize(this)-14,8,(c,p)->CustomizationPrefs.setMessageFontSize(c,14+p),p->(14+p)+" sp");
        radiusValue=slider(body,"Bubble roundness",CustomizationPrefs.getBubbleRadius(this)-4,20,(c,p)->CustomizationPrefs.setBubbleRadius(c,4+p),p->(4+p)+" dp");
        patternValue=slider(body,"Wallpaper pattern",CustomizationPrefs.getPatternIntensity(this),100,CustomizationPrefs::setPatternIntensity,p->p+"%");

        addSection(body,"Chat behavior");addSwitch(body,"Chat send / receive sounds","Play the selected sounds inside open conversations",CustomizationPrefs.chatSoundsEnabled(this),CustomizationPrefs::setChatSoundsEnabled);addSwitch(body,"Read receipts ✓✓","Show simulated double check marks",CustomizationPrefs.showReadReceipts(this),CustomizationPrefs::setShowReadReceipts);addSwitch(body,"Typing indicator","Show simulated typing state",CustomizationPrefs.showTyping(this),CustomizationPrefs::setShowTyping);addSwitch(body,"Vibration","Used by simulator notification channels",CustomizationPrefs.vibrationEnabled(this),(c,v)->{CustomizationPrefs.setVibrationEnabled(c,v);NotificationHelper.ensureChannels(c);});

        addSection(body,"Notification ringtone");soundStatus=statusLabel();body.addView(soundStatus);refreshSoundStatus();LinearLayout notifButtons=new LinearLayout(this);Button pickNotif=Ui.button(this,"Choose ringtone");pickNotif.setOnClickListener(v->pickRingtone(PICK_NOTIFICATION_SOUND,RingtoneManager.TYPE_NOTIFICATION,NotificationHelper.resolveNotificationUri(this)));notifButtons.addView(pickNotif,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));Button silentNotif=Ui.button(this,"Silent");silentNotif.setOnClickListener(v->{CustomizationPrefs.setNotificationSound(this,"silent","");NotificationHelper.ensureChannels(this);refreshSoundStatus();});notifButtons.addView(silentNotif,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));body.addView(notifButtons);Button defaultNotif=Ui.button(this,"Restore default notification tone");defaultNotif.setOnClickListener(v->{CustomizationPrefs.setNotificationSound(this,"default","");NotificationHelper.ensureChannels(this);refreshSoundStatus();preview(NotificationHelper.resolveNotificationUri(this),false);});body.addView(defaultNotif);

        addSection(body,"Call ringtone");Button callPick=Ui.button(this,"Choose simulated call ringtone");callPick.setOnClickListener(v->pickRingtone(PICK_CALL_SOUND,RingtoneManager.TYPE_RINGTONE,NotificationHelper.resolveCallUri(this)));body.addView(callPick);Button callDefault=Ui.button(this,"Restore default call ringtone");callDefault.setOnClickListener(v->{CustomizationPrefs.setCallSound(this,"default","");NotificationHelper.ensureChannels(this);preview(NotificationHelper.resolveCallUri(this),true);Toast.makeText(this,"Default call ringtone restored",Toast.LENGTH_SHORT).show();});body.addView(callDefault);

        addSection(body,"In-chat sound effects");TextView chatSoundNames=Ui.label(this,"Receive: "+CustomizationPrefs.incomingName(this)+"\nSend: "+CustomizationPrefs.outgoingName(this),13,false);chatSoundNames.setTextColor(0xFFB7C3C9);body.addView(chatSoundNames);Button chooseIn=Ui.button(this,"Choose receive sound from device");chooseIn.setOnClickListener(v->pickAudio(PICK_CHAT_IN));body.addView(chooseIn);Button resetIn=Ui.button(this,"Use built-in Receive 3");resetIn.setOnClickListener(v->{CustomizationPrefs.resetChatSound(this,true);rebuild();});body.addView(resetIn);Button chooseOut=Ui.button(this,"Choose send sound from device");chooseOut.setOnClickListener(v->pickAudio(PICK_CHAT_OUT));body.addView(chooseOut);Button resetOut=Ui.button(this,"Use built-in send sound");resetOut.setOnClickListener(v->{CustomizationPrefs.resetChatSound(this,false);rebuild();});body.addView(resetOut);Button testChat=Ui.button(this,"Preview chat sounds");testChat.setOnClickListener(v->{ChatSoundPlayer p=new ChatSoundPlayer(this);p.playOutgoing();new android.os.Handler(getMainLooper()).postDelayed(()->{p.playIncoming();new android.os.Handler(getMainLooper()).postDelayed(p::release,2200);},700);});body.addView(testChat);

        addSection(body,"Home title");titleInput=new EditText(this);titleInput.setSingleLine(true);titleInput.setText(DisplayPrefs.getHomeTitle(this));titleInput.setTextColor(Color.WHITE);titleInput.setHintTextColor(0xFF8696A0);titleInput.setBackground(Ui.rounded(0xFF1F2C33,14,this));titleInput.setPadding(Ui.dp(this,14),0,Ui.dp(this,14),0);body.addView(titleInput,new LinearLayout.LayoutParams(-1,Ui.dp(this,52)));LinearLayout sr=new LinearLayout(this);sr.setGravity(Gravity.CENTER_VERTICAL);TextView sl=Ui.label(this,"Home title size",15,true);sl.setTextColor(Color.WHITE);sr.addView(sl,new LinearLayout.LayoutParams(0,Ui.dp(this,44),1));sizeValue=Ui.label(this,DisplayPrefs.getHomeTitleSize(this)+" sp",14,true);sizeValue.setTextColor(CustomizationPrefs.accent(this));sr.addView(sizeValue);body.addView(sr);sizeSeek=new SeekBar(this);sizeSeek.setMax(20);sizeSeek.setProgress(DisplayPrefs.getHomeTitleSize(this)-18);sizeSeek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){sizeValue.setText((18+p)+" sp");}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});body.addView(sizeSeek);Button saveTitle=Ui.button(this,"Save home title");saveTitle.setOnClickListener(v->{String value=titleInput.getText().toString().trim();DisplayPrefs.setHomeTitle(this,value);DisplayPrefs.setHomeTitleSize(this,18+sizeSeek.getProgress());Toast.makeText(this,"Home title updated",Toast.LENGTH_SHORT).show();});body.addView(saveTitle);

        addSection(body,"Notification icon from gallery");notificationPreview=previewImage();body.addView(notificationPreview,previewParams());refreshNotificationPreview();Button pickNotification=Ui.button(this,"Choose notification image");pickNotification.setOnClickListener(v->pickImage(PICK_NOTIFICATION_ICON));body.addView(pickNotification);Button resetNotification=Ui.button(this,"Use default notification icon");resetNotification.setOnClickListener(v->{CustomizationHelper.resetNotificationIcon(this);refreshNotificationPreview();});body.addView(resetNotification);

        addSection(body,"Home-screen custom icon");homePreview=previewImage();body.addView(homePreview,previewParams());refreshHomePreview();Button pickHome=Ui.button(this,"Choose home icon from gallery");pickHome.setOnClickListener(v->pickImage(PICK_HOME_ICON));body.addView(pickHome);Button publish=Ui.button(this,"Add / update custom home shortcut");publish.setOnClickListener(v->{if(!CustomizationHelper.hasHomeIcon(this)){Toast.makeText(this,"Choose an image first",Toast.LENGTH_SHORT).show();return;}Toast.makeText(this,CustomizationHelper.publishOrUpdateHomeShortcut(this)?"Shortcut request sent":"Launcher rejected shortcut",Toast.LENGTH_LONG).show();});body.addView(publish);

        addSection(body,"Built-in launcher icons");Button launcher=Ui.button(this,"Choose Green / Blue / Purple / Orange / Graphite");launcher.setOnClickListener(v->chooseLauncher());body.addView(launcher);Button androidSettings=Ui.button(this,"Open Android notification settings");androidSettings.setOnClickListener(v->{Intent i=new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName());startActivity(i);});body.addView(androidSettings);

        scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));setContentView(root);
    }

    private interface IntSetter{void set(android.content.Context c,int v);}private interface ValueText{String text(int v);}private interface BoolSetter{void set(android.content.Context c,boolean v);}
    private TextView slider(LinearLayout body,String title,int progress,int max,IntSetter setter,ValueText formatter){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView t=Ui.label(this,title,15,true);t.setTextColor(Color.WHITE);row.addView(t,new LinearLayout.LayoutParams(0,Ui.dp(this,40),1));TextView val=Ui.label(this,formatter.text(progress),13,true);val.setTextColor(CustomizationPrefs.accent(this));row.addView(val);body.addView(row);SeekBar bar=new SeekBar(this);bar.setMax(max);bar.setProgress(progress);bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean from){val.setText(formatter.text(p));if(from){setter.set(CustomizationActivity.this,p);refreshLivePreview();}}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});body.addView(bar);return val;}
    private void addSwitch(LinearLayout body,String title,String sub,boolean value,BoolSetter setter){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,8));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);TextView t=Ui.label(this,title,15,true);t.setTextColor(Color.WHITE);text.addView(t);TextView s=Ui.label(this,sub,12,false);s.setTextColor(0xFF8696A0);text.addView(s);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(this);sw.setChecked(value);sw.setOnCheckedChangeListener((b,v)->setter.set(this,v));row.addView(sw);body.addView(row);}
    private void refreshLivePreview(){if(livePreview==null)return;livePreview.removeAllViews();livePreview.setBackground(new ChatPatternDrawable(this));TextView in=Ui.label(this,"مرحباً! هاي معاينة النمط 😊",CustomizationPrefs.getMessageFontSize(this),false);in.setTextColor(Color.WHITE);in.setBackground(Ui.rounded(CustomizationPrefs.incomingBubble(this),CustomizationPrefs.getBubbleRadius(this),this));in.setPadding(Ui.dp(this,10),Ui.dp(this,6),Ui.dp(this,10),Ui.dp(this,6));LinearLayout.LayoutParams a=new LinearLayout.LayoutParams(-2,-2);a.gravity=Gravity.START;a.setMargins(0,0,Ui.dp(this,40),Ui.dp(this,8));livePreview.addView(in,a);TextView out=Ui.label(this,"تمام، هيك ممتاز ✓✓",CustomizationPrefs.getMessageFontSize(this),false);out.setTextColor(Color.WHITE);out.setBackground(Ui.rounded(CustomizationPrefs.outgoingBubble(this),CustomizationPrefs.getBubbleRadius(this),this));out.setPadding(Ui.dp(this,10),Ui.dp(this,6),Ui.dp(this,10),Ui.dp(this,6));LinearLayout.LayoutParams b=new LinearLayout.LayoutParams(-2,-2);b.gravity=Gravity.END;b.setMargins(Ui.dp(this,40),0,0,0);livePreview.addView(out,b);}
    private int presetColor(String k){switch(k){case"ocean":return 0xFF0C4A6E;case"violet":return 0xFF5B3F75;case"warm":return 0xFF8A5B37;case"graphite":return 0xFF455A64;default:return 0xFF075E54;}}
    private TextView statusLabel(){TextView v=Ui.label(this,"",13,false);v.setTextColor(0xFFB7C3C9);v.setPadding(0,0,0,Ui.dp(this,8));return v;}private void refreshSoundStatus(){if(soundStatus==null)return;String m=CustomizationPrefs.getNotificationMode(this);soundStatus.setText("Current: "+("silent".equals(m)?"Silent":"custom".equals(m)?"Custom ringtone":"System default"));}
    private void pickRingtone(int req,int type,Uri existing){Intent i=new Intent(RingtoneManager.ACTION_RINGTONE_PICKER);i.putExtra(RingtoneManager.EXTRA_RINGTONE_TYPE,type);i.putExtra(RingtoneManager.EXTRA_RINGTONE_SHOW_DEFAULT,true);i.putExtra(RingtoneManager.EXTRA_RINGTONE_SHOW_SILENT,true);i.putExtra(RingtoneManager.EXTRA_RINGTONE_EXISTING_URI,existing);startActivityForResult(i,req);}
    private void pickAudio(int req){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,req);}
    private void pickImage(int code){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,code);}
    private void preview(Uri uri,boolean ring){stopPreview();if(uri==null)return;try{previewRingtone=RingtoneManager.getRingtone(this,uri);if(previewRingtone!=null){previewRingtone.setAudioAttributes(new AudioAttributes.Builder().setUsage(ring?AudioAttributes.USAGE_NOTIFICATION_RINGTONE:AudioAttributes.USAGE_NOTIFICATION).build());previewRingtone.play();}}catch(Exception ignored){}}
    private void stopPreview(){try{if(previewRingtone!=null&&previewRingtone.isPlaying())previewRingtone.stop();}catch(Exception ignored){}previewRingtone=null;}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;if(req==PICK_NOTIFICATION_SOUND||req==PICK_CALL_SOUND){Uri uri=data==null?null:data.getParcelableExtra(RingtoneManager.EXTRA_RINGTONE_PICKED_URI);boolean call=req==PICK_CALL_SOUND;if(uri==null){if(call)CustomizationPrefs.setCallSound(this,"silent","");else CustomizationPrefs.setNotificationSound(this,"silent","");}else{if(call)CustomizationPrefs.setCallSound(this,"custom",uri.toString());else CustomizationPrefs.setNotificationSound(this,"custom",uri.toString());preview(uri,call);}NotificationHelper.ensureChannels(this);refreshSoundStatus();return;}if(data==null||data.getData()==null)return;Uri uri=data.getData();try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(req==PICK_NOTIFICATION_ICON){CustomizationHelper.saveNotificationIcon(this,uri);refreshNotificationPreview();}else if(req==PICK_HOME_ICON){CustomizationHelper.saveHomeIcon(this,uri);refreshHomePreview();}else if(req==PICK_CHAT_IN){Toast.makeText(this,CustomizationPrefs.saveChatSound(this,uri,true)?"Receive sound saved":"Could not save audio",Toast.LENGTH_SHORT).show();rebuild();}else if(req==PICK_CHAT_OUT){Toast.makeText(this,CustomizationPrefs.saveChatSound(this,uri,false)?"Send sound saved":"Could not save audio",Toast.LENGTH_SHORT).show();rebuild();}}
    private void rebuild(){stopPreview();buildUi();}
    private void addSection(LinearLayout b,String v){TextView s=Ui.label(this,v,15,true);s.setTextColor(CustomizationPrefs.accent(this));s.setPadding(0,Ui.dp(this,22),0,Ui.dp(this,9));b.addView(s);}private ImageView previewImage(){ImageView i=new ImageView(this);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(Ui.rounded(0xFF1F2C33,18,this));i.setPadding(Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,8),Ui.dp(this,8));return i;}private LinearLayout.LayoutParams previewParams(){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(Ui.dp(this,92),Ui.dp(this,92));lp.gravity=Gravity.CENTER_HORIZONTAL;lp.setMargins(0,0,0,Ui.dp(this,10));return lp;}private void refreshNotificationPreview(){android.graphics.Bitmap b=CustomizationHelper.notificationLargeBitmap(this);if(b!=null)notificationPreview.setImageBitmap(b);else notificationPreview.setImageResource(R.drawable.ic_notification_custom);}private void refreshHomePreview(){android.graphics.Bitmap b=CustomizationHelper.homeIconBitmap(this);if(b!=null)homePreview.setImageBitmap(b);else homePreview.setImageResource(R.mipmap.ic_launcher);}private void chooseLauncher(){String[] v={"Green","Blue","Purple","Orange","Graphite"};String[] k={"green","blue","purple","orange","graphite"};new AlertDialog.Builder(this).setTitle("Built-in launcher icon").setItems(v,(d,w)->LauncherIconHelper.apply(this,k[w])).show();}
}
