package com.maldawr.chatsimulator;

import android.app.NotificationManager;
import android.content.Context;
import android.content.SharedPreferences;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Random;

public final class Store {
    private static final String PREFS="chat_simulator_settings_v6";
    private static final String KEY_PREFIX="prefix", KEY_CALL_SOUND="call_sound", KEY_ICON="icon", KEY_ICON_STYLE="icon_style";
    private static final String KEY_AUTOMATION="automation", KEY_ONLINE_CONTENT="online_content", KEY_WIFI_ONLY="wifi_only";
    private static final String KEY_GROUP_ACTIVITY="group_activity", KEY_EMOJI_LEVEL="emoji_level", KEY_HUMOR_LEVEL="humor_level";
    private static final String KEY_QUIET_START="quiet_start", KEY_QUIET_END="quiet_end";
    private static final Random RANDOM=new Random();
    private Store(){}

    public static final class Bot {
        public long id; public String name,phone,status,lastMessage,avatarUri,replyMode,groupSubtitle,lastSender,personality,lastTopic;
        public int unread,activeFrom,activeTo,maxBurst,emojiRate,humorRate,replyChance,quietStart,quietEnd; public long lastTime;
        public boolean autoReply,initiative,favorite,groupChat,onlineContent;
        public Bot(long id,String name,String phone){this.id=id;this.name=name;this.phone=phone;status="Fictional bot";unread=0;lastMessage="Simulation ready";lastTime=System.currentTimeMillis();autoReply=true;avatarUri="";activeFrom=0;activeTo=24;replyMode="natural";initiative=true;maxBurst=3;favorite=false;groupChat=false;groupSubtitle="";lastSender="";personality="friendly";emojiRate=45;humorRate=25;replyChance=84;onlineContent=true;quietStart=0;quietEnd=0;lastTopic="";}
    }
    public static final class Message {
        public long id,botId,time,replyToId; public String text,sender,reaction,kind; public boolean incoming;
        public Message(long id,long botId,String text,boolean incoming,long time){this(id,botId,text,incoming,time,"","",0L,"text");}
        public Message(long id,long botId,String text,boolean incoming,long time,String sender,String reaction,long replyToId,String kind){this.id=id;this.botId=botId;this.text=text==null?"":text;this.incoming=incoming;this.time=time;this.sender=sender==null?"":sender;this.reaction=reaction==null?"":reaction;this.replyToId=replyToId;this.kind=kind==null||kind.isEmpty()?"text":kind;}
    }
    public static final class CallItem { public long id,botId,time; public String type; public int durationSec; public CallItem(long id,long botId,String type,long time,int durationSec){this.id=id;this.botId=botId;this.type=type;this.time=time;this.durationSec=durationSec;} }
    public static final class GroupMember { public long id,botId; public String name,style,emoji; public int activity,humor,color; public GroupMember(long id,long botId,String name,String style,String emoji,int activity,int humor,int color){this.id=id;this.botId=botId;this.name=name;this.style=style;this.emoji=emoji;this.activity=activity;this.humor=humor;this.color=color;} }
    public static final class PlannedMessage { public String text,sender,reaction,kind; public long replyToId,delayMs; public PlannedMessage(String text,String sender,String reaction,long replyToId,String kind,long delayMs){this.text=text==null?"":text;this.sender=sender==null?"":sender;this.reaction=reaction==null?"":reaction;this.replyToId=replyToId;this.kind=kind==null||kind.isEmpty()?"text":kind;this.delayMs=Math.max(300L,delayMs);} }
    public static final class ReplyPlan { public final List<PlannedMessage> items=new ArrayList<>(); public final List<String> messages=new ArrayList<>(); public final List<Long> delaysMs=new ArrayList<>(); public String onlineTopic=""; public boolean isEmpty(){return items.isEmpty();} public void add(String text,long delay){add(text,"","",0L,"text",delay);} public void add(String text,String sender,String reaction,long replyToId,String kind,long delay){PlannedMessage p=new PlannedMessage(text,sender,reaction,replyToId,kind,delay);items.add(p);messages.add(p.text);delaysMs.add(p.delayMs);} }

    private static SharedPreferences prefs(Context c){return c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);} private static ChatDatabase.DaoApi dao(Context c){return ChatDatabase.get(c).dao();}

    public static synchronized void ensureSeeded(Context c){if(dao(c).botCount()==0)seed(c);ensureGroupMembers(c);}
    private static void seed(Context c){
        long now=System.currentTimeMillis();String[] names={"Maya","Sami","Project Team","Kareem","Family Group","Rami","Dalia","Omar"};String[] previews={"تمام، منحكي بعدين 😄","وصلتني التفاصيل","Nour: الموعد صار 9:30","تمام 👍","Lina: مين جاي بكرا؟","منحكي بكرا","شكراً إلك 🙏","تمام، شفتها"};String[] personalities={"warm","calm","work","funny","family","direct","supportive","curious"};
        List<ChatDatabase.BotRow> br=new ArrayList<>();List<ChatDatabase.MessageRow> mr=new ArrayList<>();
        for(int i=0;i<names.length;i++){Bot b=new Bot(1001+i,names[i],String.format(Locale.US,"+963 000 000 %03d",i+1));b.status="شخصية خيالية • محاكاة";b.unread=i%2==0?4:3;b.lastMessage=previews[i];b.lastTime=now-(long)(i*13+2)*60000L;b.replyMode=i==1?"slow":i==2?"instant":"natural";b.favorite=i==0||i==2||i==4;b.groupChat=i==2||i==4;b.groupSubtitle=b.groupChat?(i==2?"Maya, Nour, Sami, You":"Lina, Omar, Rami, You"):"";b.lastSender=b.groupChat?(i==2?"Nour":"Lina"):b.name;b.personality=personalities[i];b.emojiRate=35+i*6;b.humorRate=i==3||i==4?72:20+i*4;b.replyChance=i==1?74:88;b.maxBurst=b.groupChat?5:4;br.add(toRow(b));String s=b.groupChat?(i==2?"Nour":"Lina"):b.name;mr.add(toRow(new Message(now+b.id,b.id,"مرحبا، كيفك؟",true,now-3600000L,s,"",0L,"text")));mr.add(toRow(new Message(now+b.id+1,b.id,"تمام الحمد لله، وإنت؟",false,now-3420000L,"You","",0L,"text")));mr.add(toRow(new Message(now+b.id+2,b.id,b.lastMessage,true,b.lastTime,s,"",0L,"text")));}
        dao(c).putBots(br);dao(c).putMessages(mr);List<ChatDatabase.CallRow> cr=new ArrayList<>();long[] ages={1500000L,7200000L,28800000L,93600000L,259200000L};String[] types={"missed","incoming","outgoing","missed","incoming"};for(int i=0;i<ages.length;i++)cr.add(toRow(new CallItem(now+i,1001+i,types[i],now-ages[i],i%2==0?0:65+i*20)));dao(c).putCalls(cr);prefs(c).edit().putString(KEY_PREFIX,"+963").putString(KEY_ICON,"green").putString(KEY_ICON_STYLE,"rounded").putBoolean(KEY_AUTOMATION,true).putBoolean(KEY_ONLINE_CONTENT,true).putBoolean(KEY_WIFI_ONLY,false).putInt(KEY_GROUP_ACTIVITY,65).putInt(KEY_EMOJI_LEVEL,60).putInt(KEY_HUMOR_LEVEL,42).putInt(KEY_QUIET_START,1).putInt(KEY_QUIET_END,7).apply();
    }
    private static void ensureGroupMembers(Context c){for(Bot b:loadBotsRaw(c))if(b.groupChat&&dao(c).groupMemberCount(b.id)==0)dao(c).putGroupMembers(defaultMembers(b));}
    private static List<Bot> loadBotsRaw(Context c){List<Bot> r=new ArrayList<>();for(ChatDatabase.BotRow x:dao(c).botsOrdered())r.add(fromRow(x));return r;}
    private static List<ChatDatabase.GroupMemberRow> defaultMembers(Bot b){String[][] project={{"Nour","organized","📌","82","30"},{"Sami","calm","🙂","66","20"},{"Maya","friendly","✨","74","45"},{"Kareem","funny","😂","58","82"}};String[][] family={{"Lina","warm","❤️","85","48"},{"Omar","curious","🤔","63","40"},{"Rami","funny","😂","72","86"},{"Dalia","supportive","🌷","68","35"}};String[][] src=b.name.toLowerCase(Locale.ROOT).contains("family")?family:project;int[] colors={0xFFFFB36B,0xFF53BDEB,0xFF25D366,0xFFE06C9F};List<ChatDatabase.GroupMemberRow> rows=new ArrayList<>();for(int i=0;i<src.length;i++)rows.add(toRow(new GroupMember(b.id*100+i+1,b.id,src[i][0],src[i][1],src[i][2],Integer.parseInt(src[i][3]),Integer.parseInt(src[i][4]),colors[i%colors.length])));return rows;}

    private static List<Bot> bots(List<ChatDatabase.BotRow> rows){List<Bot> r=new ArrayList<>();for(ChatDatabase.BotRow x:rows)r.add(fromRow(x));return r;}
    public static List<Bot> loadBots(Context c){ensureSeeded(c);return bots(dao(c).botsOrdered());}public static List<Bot> loadUnreadBots(Context c){ensureSeeded(c);return bots(dao(c).unreadBotsOrdered());}public static List<Bot> loadFavoriteBots(Context c){ensureSeeded(c);return bots(dao(c).favoriteBotsOrdered());}public static List<Bot> loadGroupBots(Context c){ensureSeeded(c);return bots(dao(c).groupBotsOrdered());}public static int totalUnread(Context c){ensureSeeded(c);return dao(c).totalUnread();}public static int favoriteCount(Context c){ensureSeeded(c);return dao(c).favoriteCount();}public static int groupCount(Context c){ensureSeeded(c);return dao(c).groupCount();}
    public static Bot getBot(Context c,long id){ensureSeeded(c);ChatDatabase.BotRow x=dao(c).bot(id);return x==null?null:fromRow(x);}public static synchronized void saveBot(Context c,Bot b){normalize(b);dao(c).putBot(toRow(b));if(b.groupChat&&dao(c).groupMemberCount(b.id)==0)dao(c).putGroupMembers(defaultMembers(b));if(b.unread==0)NotificationHelper.cancelMessage(c,b.id);}public static void setFavorite(Context c,long id,boolean v){dao(c).setFavorite(id,v);}public static synchronized void markRead(Context c,long id){dao(c).markRead(id);NotificationHelper.cancelMessage(c,id);}
    public static List<Message> loadMessages(Context c,long id){ensureSeeded(c);List<Message> r=new ArrayList<>();for(ChatDatabase.MessageRow x:dao(c).messages(id))r.add(fromRow(x));return r;}public static Message getMessage(Context c,long id){ChatDatabase.MessageRow x=dao(c).message(id);return x==null?null:fromRow(x);}public static List<Message> recentMessages(Context c,long id,int limit){List<Message> all=loadMessages(c,id);int start=Math.max(0,all.size()-Math.max(1,limit));return new ArrayList<>(all.subList(start,all.size()));}
    public static synchronized void addMessage(Context c,Message m){ensureSeeded(c);if(m.id==0)m.id=nextMessageId();dao(c).putMessage(toRow(m));if("reaction_event".equals(m.kind))return;Bot b=getBot(c,m.botId);if(b==null)return;b.lastMessage=m.text;b.lastTime=m.time;b.lastSender=m.incoming?(!m.sender.isEmpty()?m.sender:b.name):"You";b.unread=m.incoming?(ChatActivity.isConversationVisible(m.botId)?0:Math.min(99,b.unread+1)):0;dao(c).putBot(toRow(b));if(b.unread==0)NotificationHelper.cancelMessage(c,b.id);}
    public static synchronized void applyReaction(Context c,long botId,long targetId,String reaction,String sender){if(targetId<=0||reaction==null||reaction.isEmpty())return;dao(c).setReaction(targetId,reaction);dao(c).putMessage(toRow(new Message(nextMessageId(),botId,"",true,System.currentTimeMillis(),sender,reaction,targetId,"reaction_event")));}
    public static List<GroupMember> loadGroupMembers(Context c,long id){ensureSeeded(c);List<GroupMember> r=new ArrayList<>();for(ChatDatabase.GroupMemberRow x:dao(c).groupMembers(id))r.add(fromRow(x));return r;}public static synchronized void replaceGroupMembers(Context c,long id,List<GroupMember> members){dao(c).clearGroupMembers(id);List<ChatDatabase.GroupMemberRow> rows=new ArrayList<>();for(GroupMember m:members)rows.add(toRow(m));dao(c).putGroupMembers(rows);}
    public static List<CallItem> loadCalls(Context c){ensureSeeded(c);List<CallItem>r=new ArrayList<>();for(ChatDatabase.CallRow x:dao(c).calls())r.add(fromRow(x));return r;}public static synchronized void addCall(Context c,CallItem x){dao(c).putCall(toRow(x));}
    public static ReplyPlan buildReplyPlan(Context c,Bot b,String input){return ConversationEngine.planForUserMessage(c,b,input);}public static ReplyPlan buildReplyPlan(Bot b,String input){ReplyPlan p=new ReplyPlan();if(b!=null&&b.autoReply)p.add(smartReply(input),b.name,"",0L,"text",1500L);return p;}
    public static String smartReply(String input){String x=input==null?"":input.toLowerCase(Locale.ROOT);if(x.contains("مرحبا")||x.contains("هلا"))return"أهلا 😊";if(x.contains("شكرا")||x.contains("شكراً"))return"العفو 🙏";if(x.contains("موعد")||x.contains("وقت"))return"تمام، ابعتلي الوقت المناسب.";if(x.contains("وين"))return"بالطريق تقريباً، بعطيك خبر أول ما أوصل.";return"تمام 👍";}
    public static long nextMessageId(){return System.currentTimeMillis()*1000L+RANDOM.nextInt(1000);}public static String formatTime(long t){return new SimpleDateFormat("h:mm a",Locale.getDefault()).format(new Date(t));}public static String formatDateTime(long t){return new SimpleDateFormat("MMM d, h:mm a",Locale.getDefault()).format(new Date(t));}
    public static String getPrefix(Context c){return prefs(c).getString(KEY_PREFIX,"+963");}public static void setPrefix(Context c,String v){prefs(c).edit().putString(KEY_PREFIX,v==null?"+963":v).apply();}public static String getCallSound(Context c){return prefs(c).getString(KEY_CALL_SOUND,"");}public static void setCallSound(Context c,String v){prefs(c).edit().putString(KEY_CALL_SOUND,v==null?"":v).apply();}public static String getIcon(Context c){return prefs(c).getString(KEY_ICON,"green");}public static void setIcon(Context c,String v){prefs(c).edit().putString(KEY_ICON,v).apply();}public static String getIconStyle(Context c){return prefs(c).getString(KEY_ICON_STYLE,"rounded");}public static void setIconStyle(Context c,String v){prefs(c).edit().putString(KEY_ICON_STYLE,v).apply();}
    public static boolean isAutomationEnabled(Context c){return prefs(c).getBoolean(KEY_AUTOMATION,true);}public static void setAutomationEnabled(Context c,boolean v){prefs(c).edit().putBoolean(KEY_AUTOMATION,v).apply();}public static boolean isOnlineContentEnabled(Context c){return prefs(c).getBoolean(KEY_ONLINE_CONTENT,true);}public static void setOnlineContentEnabled(Context c,boolean v){prefs(c).edit().putBoolean(KEY_ONLINE_CONTENT,v).apply();}public static boolean isWifiOnly(Context c){return prefs(c).getBoolean(KEY_WIFI_ONLY,false);}public static void setWifiOnly(Context c,boolean v){prefs(c).edit().putBoolean(KEY_WIFI_ONLY,v).apply();}public static int getGroupActivity(Context c){return prefs(c).getInt(KEY_GROUP_ACTIVITY,65);}public static void setGroupActivity(Context c,int v){prefs(c).edit().putInt(KEY_GROUP_ACTIVITY,clamp(v,0,100)).apply();}public static int getEmojiLevel(Context c){return prefs(c).getInt(KEY_EMOJI_LEVEL,60);}public static void setEmojiLevel(Context c,int v){prefs(c).edit().putInt(KEY_EMOJI_LEVEL,clamp(v,0,100)).apply();}public static int getHumorLevel(Context c){return prefs(c).getInt(KEY_HUMOR_LEVEL,42);}public static void setHumorLevel(Context c,int v){prefs(c).edit().putInt(KEY_HUMOR_LEVEL,clamp(v,0,100)).apply();}public static int getQuietStart(Context c){return prefs(c).getInt(KEY_QUIET_START,1);}public static void setQuietStart(Context c,int v){prefs(c).edit().putInt(KEY_QUIET_START,clamp(v,0,23)).apply();}public static int getQuietEnd(Context c){return prefs(c).getInt(KEY_QUIET_END,7);}public static void setQuietEnd(Context c,int v){prefs(c).edit().putInt(KEY_QUIET_END,clamp(v,0,23)).apply();}
    public static boolean isGlobalQuietTime(Context c){return isHourInside(Calendar.getInstance().get(Calendar.HOUR_OF_DAY),getQuietStart(c),getQuietEnd(c));}public static boolean isBotActive(Bot b){int h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY);return isActiveWindow(h,b.activeFrom,b.activeTo)&&!isHourInside(h,b.quietStart,b.quietEnd);}private static boolean isActiveWindow(int h,int s,int e){if(s==e)return true;if(s<e)return h>=s&&h<e;return h>=s||h<e;}private static boolean isHourInside(int h,int s,int e){if(s==e)return false;if(s<e)return h>=s&&h<e;return h>=s||h<e;}
    public static synchronized void resetDemo(Context c){ChatDatabase.DaoApi d=dao(c);d.clearMessages();d.clearCalls();d.clearAllGroupMembers();d.clearBots();seed(c);ensureGroupMembers(c);NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.cancelAll();}
    private static void normalize(Bot b){if(b.name==null||b.name.trim().isEmpty())b.name="Fictional Bot";if(b.phone==null)b.phone="";if(b.status==null)b.status="شخصية خيالية • محاكاة";if(b.lastMessage==null)b.lastMessage="";if(b.avatarUri==null)b.avatarUri="";if(b.replyMode==null||b.replyMode.isEmpty())b.replyMode="natural";if(b.groupSubtitle==null)b.groupSubtitle="";if(b.lastSender==null)b.lastSender="";if(b.personality==null||b.personality.isEmpty())b.personality="friendly";if(b.lastTopic==null)b.lastTopic="";b.emojiRate=clamp(b.emojiRate,0,100);b.humorRate=clamp(b.humorRate,0,100);b.replyChance=clamp(b.replyChance,0,100);b.maxBurst=clamp(b.maxBurst,1,5);}private static int clamp(int v,int min,int max){return Math.max(min,Math.min(max,v));}
    private static ChatDatabase.BotRow toRow(Bot b){normalize(b);ChatDatabase.BotRow x=new ChatDatabase.BotRow();x.id=b.id;x.name=b.name;x.phone=b.phone;x.status=b.status;x.unread=b.unread;x.lastMessage=b.lastMessage;x.lastTime=b.lastTime;x.autoReply=b.autoReply;x.avatarUri=b.avatarUri;x.activeFrom=b.activeFrom;x.activeTo=b.activeTo;x.replyMode=b.replyMode;x.initiative=b.initiative;x.maxBurst=b.maxBurst;x.favorite=b.favorite;x.groupChat=b.groupChat;x.groupSubtitle=b.groupSubtitle;x.lastSender=b.lastSender;x.personality=b.personality;x.emojiRate=b.emojiRate;x.humorRate=b.humorRate;x.replyChance=b.replyChance;x.onlineContent=b.onlineContent;x.quietStart=b.quietStart;x.quietEnd=b.quietEnd;x.lastTopic=b.lastTopic;return x;}
    private static Bot fromRow(ChatDatabase.BotRow x){Bot b=new Bot(x.id,x.name,x.phone);b.status=x.status;b.unread=x.unread;b.lastMessage=x.lastMessage;b.lastTime=x.lastTime;b.autoReply=x.autoReply;b.avatarUri=x.avatarUri;b.activeFrom=x.activeFrom;b.activeTo=x.activeTo;b.replyMode=x.replyMode;b.initiative=x.initiative;b.maxBurst=x.maxBurst;b.favorite=x.favorite;b.groupChat=x.groupChat;b.groupSubtitle=x.groupSubtitle;b.lastSender=x.lastSender;b.personality=x.personality;b.emojiRate=x.emojiRate;b.humorRate=x.humorRate;b.replyChance=x.replyChance;b.onlineContent=x.onlineContent;b.quietStart=x.quietStart;b.quietEnd=x.quietEnd;b.lastTopic=x.lastTopic;normalize(b);return b;}
    private static ChatDatabase.MessageRow toRow(Message m){ChatDatabase.MessageRow x=new ChatDatabase.MessageRow();x.id=m.id;x.botId=m.botId;x.text=m.text;x.incoming=m.incoming;x.time=m.time;x.sender=m.sender;x.reaction=m.reaction;x.replyToId=m.replyToId;x.kind=m.kind;return x;}private static Message fromRow(ChatDatabase.MessageRow x){return new Message(x.id,x.botId,x.text,x.incoming,x.time,x.sender,x.reaction,x.replyToId,x.kind);}private static ChatDatabase.CallRow toRow(CallItem c){ChatDatabase.CallRow x=new ChatDatabase.CallRow();x.id=c.id;x.botId=c.botId;x.type=c.type;x.time=c.time;x.durationSec=c.durationSec;return x;}private static CallItem fromRow(ChatDatabase.CallRow x){return new CallItem(x.id,x.botId,x.type,x.time,x.durationSec);}private static ChatDatabase.GroupMemberRow toRow(GroupMember m){ChatDatabase.GroupMemberRow x=new ChatDatabase.GroupMemberRow();x.id=m.id;x.botId=m.botId;x.name=m.name;x.style=m.style;x.emoji=m.emoji;x.activity=m.activity;x.humor=m.humor;x.color=m.color;return x;}private static GroupMember fromRow(ChatDatabase.GroupMemberRow x){return new GroupMember(x.id,x.botId,x.name,x.style,x.emoji,x.activity,x.humor,x.color);}
}
